name: gp_enso
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - selenium
  - scipy
  - matplotlib
  - bokeh
  - pymc
  - arviz
  - statsmodels
  - scikit-learn
  - pip
  - requests
